### ISSUE TITLE
Missing information in documents when built

### ISSUE THREAD

**Issue by paulieguk** [MicrosoftLearning/20703-IntegratingMDMandCloudServiceswithSCCM#2]
There seems to be an issue when building these documents with Pandoc.  Information disappears from the final document but it is in the md document.  It seems to be where there is a '\' character.  Within the document data between ** & ** is set to bold but this data will often contain the backslash (e.g. account or file names).  This corrupts the data.  For Example In Lab answer key 1 Exercise 2 Task 1 step 1 the data in the md document is fine (ADATUM\Administrator) but it has become ADATUM* in the word document.  The documents are covered with this issue.  I have tried various version of Pandoc including the version in the instructor guide 1.19.2.

**Comment by ckezema** [comment]
Backslash issue has been fixed
