### ISSUE TITLE
Office 365 Trial requires a credit card

### ISSUE THREAD

**Issue by itbland** [MicrosoftLearning/20703-IntegratingMDMandCloudServiceswithSCCM#3]
Same issue as reported in this [20697-2 Issue](https://github.com/MicrosoftLearning/20697-2-DeployingManagingWindows10/issues/7)
In Mod 04, a credit card is required for Office 365 - Looks like there's no way around it.

**Comment by StanReimer** [comment]
Xtreme rolled out a solution this week where they provide a precreated account so students don't have to enter any credit card info. It sounds like other hosting providers are looking at doing something similar. Still waiting to hear an answer for non hosted labs.

**Comment by ckezema** [comment]
For this course (20703-2A), you can use the Office 365 ProPlus subscription. This subscription does not require any credit card at this time.
